# GoReleaser configuration for connection-cli
project_name: connection-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: connection-cli
    main: ./cmd
    binary: connection-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Publish to GitHub Releases
release:
  github:
    owner: LemonZuo
    name: connection-cli
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{ .Version }}" 